#!/usr/bin/env ruby

require "bundler/setup"
require "dogen"
include Dogen

def banner_and_exit
  puts Dogen::CLI::BANNER
  exit
end

arg1 = ARGV.shift
arg2 = ARGV.shift
banner_and_exit unless arg1

if arg1.downcase == '$ample'
  CLI.sample
  exit
end

CLI.dogen(arg1)
